server:
  port: 8787
  tomcat:
#    uri-encoding: UTF-8 # URI编码，默认"ISO-8859-1"
    max-threads: 300
    max-connections: 200
    accept-count: 100
    basedir: /data/webroot/jpa-sample
    accesslog:
      enabled: true

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  config: classpath:config/log4j2.xml


